=== Islamsulaiman/ITI-Scholorship-Subjects-labs/xml/day2/lab2/src/Question2/main.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->


<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="LibraryManual"/>
        <xs:element name="book">
            
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="author"/>
              <xs:element type="xs:string" name="preface"/>
              <xs:element name="part" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                    
                  <xs:sequence>
                    <xs:element name="chapter">
                      <xs:complexType>
                          
                        <xs:sequence>
                          <xs:element type="xs:string" name="summary"/>
                          <xs:element name="content">
                              
                            <xs:complexType>       
                              <xs:sequence>
                                <xs:element type="xs:string" name="p"/>
                              </xs:sequence>
                            </xs:complexType>
                            
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="chap_title" use="optional"/>
                      </xs:complexType>
                      
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="part_title" use="optional"/>
                </xs:complexType>
                
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="isbn"/>
            <xs:attribute type="xs:string" name="book_title"/>
          </xs:complexType>
          
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="location"/>
      <xs:attribute type="xs:string" name="description"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Islamsulaiman/ITI-Scholorship-Subjects-labs/xml/day2/lab2/src/Question2/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="main.xsd"
    location="Al4arqya abookbeer" description="it's a lib">

    <LibraryManual>ITI</LibraryManual>
    <book isbn="1" book_title="eatLovePray">
        <author>Islam sulaiman</author>
        <preface>Hello</preface>


        <part part_title="part">
            
            <chapter chap_title="chapter">
                <summary>Looma</summary>
                <content>
                    <p>From hell</p>
                </content>
            </chapter>
            
        </part>
        
        
       
        
        <part part_title="part">
            <chapter chap_title="chapter">
                <summary>chap1 about iti</summary>
                <content>
                    <p>Some text here about the book</p>
                </content>
            </chapter>
        </part>
    </book>
    

</library>
